### PR TITLE
add support for _db_updates feed

### PR DESCRIPTION
**Pull request by skscharr**
Copy same format of _changes feed for _db_updates.

@evansde77

### CODE REVIEW

**Comment by evansde77** [comment]
Cool! Test coverage?

**Comment by skscharr** [comment]
brain not awake enough to figure out mocking the Feed() object so putting that bit off for now

**Comment by pengale** [comment]
Code makes sense. Would give a +1 after tests verified that it works :-)

**Comment by evansde77** [comment]
+1

**Comment by pengale** [comment]
LGTM/+1

**Pull request merged**
